version: '3'

services:
  notecode:
    build: api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://app_db:5432/notecode
      DB_USER_NAME: myuser
      DB_PASSWORD: admin
      UPLOADS_DIRECTORY: "/app/uploads"
    restart: always
    volumes:
      - ./api/uploads:/app/uploads
    depends_on:
      app_db:
        condition: service_healthy
  app_db:
    image: postgres:17-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: notecode
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: admin
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d notecode" ]
      interval: 10s
      timeout: 5s
      retries: 5